name: CI/CD Pipeline with Jenkins Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Validate Maven project
      run: mvn validate
      
    - name: Compile source code
      run: mvn clean compile
      
    - name: Run unit tests
      run: mvn test
      
    - name: Package application
      run: mvn package -DskipTests

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Jenkins Deployment Job
      run: |
        echo "Triggering Jenkins deployment..."
        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
          "${{ secrets.JENKINS_URL }}/job/insured-assurance-pipeline/build?token=${{ secrets.JENKINS_JOB_TOKEN }}" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}")
        
        if [ $response -eq 201 ]; then
          echo "✅ Jenkins job triggered successfully"
        else
          echo "❌ Failed to trigger Jenkins job. HTTP status: $response"
          exit 1
        fi
